main: "com.thevoxelbox.voxelsniper.VoxelSniperPlugin"
name: "VoxelSniper"
version: "1.0.2-cloudburst"
description: "World editing from ingame using 3D brushes"
api-version: "2.0.0"
authors:
  - "przerwap"
  - "MikeMatrix"
  - "Gavjenks"
  - "giltwist"
  - "psanker"
  - "Deamon5550"
  - "DivineRage"
  - "pitcer"
  - "jaqobb"
  - "DaPorkchop_"
website: "https://github.com/DaMatrix/VoxelSniper-Cloudburst"
